service: weekly-tweet
frameworkVersion: "3"
configValidationMode: warn

package:
  artifact: .build/plugins/AWSLambdaPackager/outputs/AWSLambdaPackager/WeeklyTweetCronJob/WeeklyTweetCronJob.zip

provider:
  name: aws
  region: eu-west-1
  httpApi:
    payload: "2.0"
    cors: true
  runtime: provided
  architecture: x86_64

functions:
  tweet:
    handler: tweet
    memorySize: 256
    description: "[${sls:stage}] Tweet"
    environment:
      FATHOM_ENTITY_ID: ${env:FATHOM_ENTITY_ID}
      TWITTER_API_KEY: ${env:TWITTER_API_KEY}
      TWITTER_API_SECRET: ${env:TWITTER_API_SECRET}
      TWITTER_API_TOKEN: ${env:TWITTER_API_TOKEN}
      TWITTER_API_TOKEN_SECRET: ${env:TWITTER_API_TOKEN_SECRET}
    events:
      - eventBridge:
          schedule: cron(0 12 ? * FRI *)
