service: weekly-tweet
frameworkVersion: "3"
configValidationMode: warn

package:
  artifact: .build/plugins/AWSLambdaPackager/outputs/AWSLambdaPackager/WeeklyTweetCronJob/WeeklyTweetCronJob.zip

provider:
  name: aws
  region: eu-west-1
  httpApi:
    payload: "2.0"
    cors: true
  runtime: provided
  architecture: x86_64

functions:
  tweet:
    handler: tweet
    memorySize: 256
    description: "[${sls:stage}] Tweet"
    events:
      - eventBridge:
          schedule: cron(0 12 ? * FRI *)
