name: Tweet most read posts

on:
  schedule:
    - cron: 0 12 * * 5
  workflow_dispatch:
jobs:
  tweet:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3
      - run: swift run -c release WeeklyTweetCronJob
        env:
          FATHOM_ENTITY_ID: ${{Secrets.FATHOM_ENTITY_ID}}
          FATHOM_TOKEN: ${{Secrets.FATHOM_TOKEN}}
          TWITTER_API_KEY: ${{Secrets.TWITTER_API_KEY}}
          TWITTER_API_SECRET: ${{Secrets.TWITTER_API_SECRET}}
          TWITTER_API_TOKEN: ${{Secrets.TWITTER_API_TOKEN}}
          TWITTER_API_TOKEN_SECRET: ${{Secrets.TWITTER_API_TOKEN_SECRET}}
